"""Tests for L22.3: POST /executor/task unified entry and handle_task_from_api.

Covers:
  - executor_api: POST /executor/task → 200 with task_id/observer_token/observer_url
  - executor_api: POST /executor/task missing message → 400
  - executor_api: GET /executor/task/{id}/observe → status from observer session
  - executor_api: observe unknown task_id → 404
  - executor_api: _observer_sessions populated after submit
  - task_orchestrator: handle_task_from_api writes task file to pending/
  - task_orchestrator: handle_task_from_api uses atomic rename (no .tmp left)
  - task_orchestrator: handle_task_from_api task data has required fields
  - task_orchestrator: handle_task_from_api updates observer session status
"""

import json
import os
import sys
import tempfile
import threading
import time
import unittest
import urllib.request
import urllib.error
from pathlib import Path
from unittest.mock import patch, MagicMock

REPO_ROOT = Path(__file__).resolve().parents[2]
AGENT_DIR = REPO_ROOT / "agent"
if str(AGENT_DIR) not in sys.path:
    sys.path.insert(0, str(AGENT_DIR))


def _find_free_port() -> int:
    import socket
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _post_json(url: str, payload: dict, timeout: int = 5) -> tuple[int, dict]:
    data = json.dumps(payload).encode()
    req = urllib.request.Request(
        url, data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


def _get_json(url: str, timeout: int = 5) -> tuple[int, dict]:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


class TestExecutorApiSubmitTask(unittest.TestCase):
    """Integration tests for POST /executor/task via HTTP."""

    def setUp(self):
        self._tmpdir = tempfile.TemporaryDirectory()
        self._shared_root = Path(self._tmpdir.name)
        (self._shared_root / "codex-tasks" / "pending").mkdir(parents=True)

        port = _find_free_port()
        self._port = port
        self._base = f"http://127.0.0.1:{port}"

        # Reset executor_api module globals
        import executor_api
        executor_api._orchestrator = None
        executor_api._observer_sessions.clear()

        # Start server with patched port and shared volume
        from http.server import HTTPServer
        server = HTTPServer(("127.0.0.1", port), executor_api.ExecutorAPIHandler)
        self._server = server
        t = threading.Thread(target=server.serve_forever, daemon=True)
        t.start()
        time.sleep(0.15)

    def tearDown(self):
        self._server.shutdown()
        self._tmpdir.cleanup()
        import executor_api
        executor_api._orchestrator = None
        executor_api._observer_sessions.clear()

    def test_submit_returns_200_with_required_fields(self):
        """POST /executor/task with valid body returns 200 and required fields."""
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            status, body = _post_json(f"{self._base}/executor/task", {
                "source": "api",
                "session_type": "task",
                "message": "implement feature X",
                "project_id": "test_project",
            })
        self.assertEqual(status, 200, body)
        self.assertIn("task_id", body)
        self.assertIn("observer_token", body)
        self.assertIn("observer_url", body)
        self.assertEqual(body["status"], "accepted")

    def test_submit_task_id_starts_with_task_api(self):
        """task_id generated by submit should start with 'task-api-'."""
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            _, body = _post_json(f"{self._base}/executor/task", {
                "message": "do something",
            })
        self.assertTrue(body["task_id"].startswith("task-api-"), body["task_id"])

    def test_submit_observer_url_contains_task_id(self):
        """observer_url should embed the returned task_id."""
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            _, body = _post_json(f"{self._base}/executor/task", {
                "message": "do something",
            })
        self.assertIn(body["task_id"], body["observer_url"])

    def test_submit_missing_message_returns_400(self):
        """POST without 'message' field returns 400."""
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            status, body = _post_json(f"{self._base}/executor/task", {
                "source": "api",
            })
        self.assertEqual(status, 400)
        self.assertIn("error", body)

    def test_submit_empty_message_returns_400(self):
        """POST with empty string 'message' returns 400."""
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            status, body = _post_json(f"{self._base}/executor/task", {
                "message": "",
            })
        self.assertEqual(status, 400)

    def test_submit_registers_observer_session(self):
        """After submit, _observer_sessions should contain entry for returned task_id."""
        import executor_api
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            _, body = _post_json(f"{self._base}/executor/task", {
                "message": "test task",
                "source": "telegram",
                "session_type": "chat",
            })
        task_id = body["task_id"]
        self.assertIn(task_id, executor_api._observer_sessions)
        session = executor_api._observer_sessions[task_id]
        self.assertEqual(session["token"], body["observer_token"])
        self.assertEqual(session["source"], "telegram")
        self.assertEqual(session["session_type"], "chat")

    def test_submit_calls_orchestrator_in_background(self):
        """When orchestrator is set, handle_task_from_api is called asynchronously."""
        import executor_api

        called_args = {}

        def fake_handle(task_id, payload):
            called_args["task_id"] = task_id
            called_args["payload"] = payload

        mock_orch = MagicMock()
        mock_orch.handle_task_from_api = fake_handle
        executor_api._orchestrator = mock_orch

        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            _, body = _post_json(f"{self._base}/executor/task", {
                "message": "run pipeline",
                "project_id": "proj1",
                "chat_id": 12345,
            })

        # Wait for background thread
        deadline = time.time() + 3
        while "task_id" not in called_args and time.time() < deadline:
            time.sleep(0.05)

        self.assertIn("task_id", called_args, "orchestrator.handle_task_from_api was not called")
        self.assertEqual(called_args["task_id"], body["task_id"])
        self.assertEqual(called_args["payload"]["message"], "run pipeline")
        self.assertEqual(called_args["payload"]["project_id"], "proj1")
        self.assertEqual(called_args["payload"]["chat_id"], 12345)

    def test_submit_returns_immediately_without_orchestrator(self):
        """Without orchestrator, submit still returns 200 (no blocking)."""
        import executor_api
        executor_api._orchestrator = None

        start = time.time()
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            status, body = _post_json(f"{self._base}/executor/task", {
                "message": "test",
            })
        elapsed = time.time() - start
        self.assertEqual(status, 200)
        self.assertLess(elapsed, 2.0, "Submit should be fast even without orchestrator")


class TestExecutorApiObserveTask(unittest.TestCase):
    """Tests for GET /executor/task/{task_id}/observe."""

    def setUp(self):
        self._tmpdir = tempfile.TemporaryDirectory()
        self._shared_root = Path(self._tmpdir.name)
        for stage in ("pending", "processing", "results"):
            (self._shared_root / "codex-tasks" / stage).mkdir(parents=True)

        port = _find_free_port()
        self._port = port
        self._base = f"http://127.0.0.1:{port}"

        import executor_api
        executor_api._orchestrator = None
        executor_api._observer_sessions.clear()

        from http.server import HTTPServer
        server = HTTPServer(("127.0.0.1", port), executor_api.ExecutorAPIHandler)
        self._server = server
        t = threading.Thread(target=server.serve_forever, daemon=True)
        t.start()
        time.sleep(0.15)

    def tearDown(self):
        self._server.shutdown()
        self._tmpdir.cleanup()
        import executor_api
        executor_api._observer_sessions.clear()

    def _register(self, task_id, status="accepted", source="api"):
        import executor_api
        from datetime import datetime, timezone
        executor_api._observer_sessions[task_id] = {
            "token": "tok-abc",
            "status": status,
            "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "source": source,
            "session_type": "task",
            "project_id": "testproj",
        }

    def test_observe_unknown_task_returns_404(self):
        """GET observe for unknown task_id returns 404."""
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            status, body = _get_json(f"{self._base}/executor/task/no-such-id/observe")
        self.assertEqual(status, 404)

    def test_observe_accepted_task_returns_200(self):
        """After submit, observe returns 200 with status field."""
        task_id = "task-api-observe-001"
        self._register(task_id, "accepted")
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            status, body = _get_json(f"{self._base}/executor/task/{task_id}/observe")
        self.assertEqual(status, 200)
        self.assertEqual(body["task_id"], task_id)
        self.assertIn("status", body)

    def test_observe_task_in_pending_shows_queued(self):
        """Task file in pending/ → status 'queued'."""
        task_id = "task-api-pend-001"
        self._register(task_id)
        (self._shared_root / "codex-tasks" / "pending" / f"{task_id}.json").write_text("{}")
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            _, body = _get_json(f"{self._base}/executor/task/{task_id}/observe")
        self.assertEqual(body["status"], "queued")

    def test_observe_task_in_processing_shows_running(self):
        """Task file in processing/ → status 'running'."""
        task_id = "task-api-proc-001"
        self._register(task_id)
        (self._shared_root / "codex-tasks" / "processing" / f"{task_id}.json").write_text("{}")
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            _, body = _get_json(f"{self._base}/executor/task/{task_id}/observe")
        self.assertEqual(body["status"], "running")

    def test_observe_task_in_results_shows_completed(self):
        """Task file in results/ → status 'completed'."""
        task_id = "task-api-res-001"
        self._register(task_id)
        (self._shared_root / "codex-tasks" / "results" / f"{task_id}.json").write_text("{}")
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            _, body = _get_json(f"{self._base}/executor/task/{task_id}/observe")
        self.assertEqual(body["status"], "completed")

    def test_observe_response_includes_observer_token(self):
        """observe response contains the observer_token for the task."""
        task_id = "task-api-tok-001"
        self._register(task_id)
        with patch.dict(os.environ, {"SHARED_VOLUME_PATH": str(self._shared_root)}):
            _, body = _get_json(f"{self._base}/executor/task/{task_id}/observe")
        self.assertEqual(body["observer_token"], "tok-abc")


class TestHandleTaskFromApi(unittest.TestCase):
    """Unit tests for TaskOrchestrator.handle_task_from_api."""

    def setUp(self):
        self._tmpdir = tempfile.TemporaryDirectory()
        self._shared_root = Path(self._tmpdir.name)
        self._pending = self._shared_root / "codex-tasks" / "pending"
        self._pending.mkdir(parents=True)
        self._env = {
            "SHARED_VOLUME_PATH": str(self._shared_root),
            "GOVERNANCE_URL": "http://localhost:40000",
            "GOV_COORDINATOR_TOKEN": "test-token",
        }

    def tearDown(self):
        self._tmpdir.cleanup()

    def _make_orchestrator(self):
        """Create TaskOrchestrator with heavy dependencies mocked out."""
        with patch("ai_lifecycle.AILifecycleManager"), \
             patch("context_assembler.ContextAssembler"), \
             patch("decision_validator.DecisionValidator"), \
             patch("decision_validator.build_retry_prompt"), \
             patch("graph_validator.GraphValidator"), \
             patch("evidence_collector.EvidenceCollector"), \
             patch("ai_output_parser.parse_ai_output"):
            from task_orchestrator import TaskOrchestrator
            orch = TaskOrchestrator()
        return orch

    def test_writes_task_file_to_pending(self):
        """handle_task_from_api creates a .json file in pending/."""
        orch = self._make_orchestrator()
        task_id = "task-api-unit-001"
        payload = {
            "source": "api",
            "session_type": "task",
            "message": "fix the bug in auth module",
            "project_id": "proj_test",
            "chat_id": 0,
        }
        with patch.dict(os.environ, self._env), \
             patch("requests.post"):  # suppress DB/gateway calls
            orch.handle_task_from_api(task_id, payload)

        task_file = self._pending / f"{task_id}.json"
        self.assertTrue(task_file.exists(), "task file not written to pending/")

    def test_no_tmp_file_left_after_write(self):
        """Atomic rename: no .tmp.json should remain after write."""
        orch = self._make_orchestrator()
        task_id = "task-api-unit-002"
        payload = {"message": "test", "project_id": "proj_test"}
        with patch.dict(os.environ, self._env), \
             patch("requests.post"):
            orch.handle_task_from_api(task_id, payload)

        tmp_file = self._pending / f"{task_id}.tmp.json"
        self.assertFalse(tmp_file.exists(), ".tmp.json should be removed after rename")

    def test_task_data_has_required_fields(self):
        """Written task file contains all required fields for Executor routing."""
        orch = self._make_orchestrator()
        task_id = "task-api-unit-003"
        payload = {
            "source": "telegram",
            "session_type": "dev_task",
            "message": "implement login feature",
            "project_id": "my_project",
            "chat_id": 99,
        }
        with patch.dict(os.environ, self._env), \
             patch("requests.post"):
            orch.handle_task_from_api(task_id, payload)

        with open(self._pending / f"{task_id}.json") as f:
            data = json.load(f)

        for field in ("task_id", "project_id", "text", "prompt", "action",
                      "type", "chat_id", "created_at", "_chain_depth", "_source"):
            self.assertIn(field, data, f"Missing field: {field}")

        self.assertEqual(data["task_id"], task_id)
        self.assertEqual(data["project_id"], "my_project")
        self.assertEqual(data["prompt"], "implement login feature")
        self.assertEqual(data["type"], "dev_task")
        self.assertEqual(data["chat_id"], 99)
        self.assertEqual(data["_source"], "telegram")
        self.assertEqual(data["_chain_depth"], 0)

    def test_task_data_action_is_claude(self):
        """action field defaults to 'claude' for Executor routing."""
        orch = self._make_orchestrator()
        task_id = "task-api-unit-004"
        with patch.dict(os.environ, self._env), \
             patch("requests.post"):
            orch.handle_task_from_api(task_id, {"message": "do work"})

        with open(self._pending / f"{task_id}.json") as f:
            data = json.load(f)
        self.assertEqual(data["action"], "claude")

    def test_default_project_id_fallback(self):
        """When project_id is absent, defaults to 'amingClaw'."""
        orch = self._make_orchestrator()
        task_id = "task-api-unit-005"
        with patch.dict(os.environ, self._env), \
             patch("requests.post"):
            orch.handle_task_from_api(task_id, {"message": "something"})

        with open(self._pending / f"{task_id}.json") as f:
            data = json.load(f)
        self.assertEqual(data["project_id"], "amingClaw")

    def test_updates_observer_session_status(self):
        """handle_task_from_api updates executor_api._observer_sessions status to 'queued'."""
        import executor_api
        task_id = "task-api-unit-006"
        executor_api._observer_sessions[task_id] = {
            "token": "tok-xyz",
            "status": "accepted",
        }

        orch = self._make_orchestrator()
        with patch.dict(os.environ, self._env), \
             patch("requests.post"):
            orch.handle_task_from_api(task_id, {"message": "run tests"})

        self.assertEqual(
            executor_api._observer_sessions[task_id]["status"],
            "queued",
            "Observer session status should be updated to 'queued'",
        )

    def test_db_failure_does_not_abort_file_write(self):
        """If governance DB is unreachable, file write still succeeds."""
        import requests as _req

        def raise_on_post(*a, **kw):
            raise ConnectionError("governance down")

        orch = self._make_orchestrator()
        task_id = "task-api-unit-007"
        with patch.dict(os.environ, self._env), \
             patch("requests.post", side_effect=raise_on_post):
            orch.handle_task_from_api(task_id, {"message": "still works"})

        self.assertTrue(
            (self._pending / f"{task_id}.json").exists(),
            "Task file must be written even when DB is unreachable",
        )

    def test_created_at_is_iso_format(self):
        """created_at in task file is ISO-8601 UTC timestamp."""
        import re
        orch = self._make_orchestrator()
        task_id = "task-api-unit-008"
        with patch.dict(os.environ, self._env), \
             patch("requests.post"):
            orch.handle_task_from_api(task_id, {"message": "check time"})

        with open(self._pending / f"{task_id}.json") as f:
            data = json.load(f)
        self.assertRegex(
            data["created_at"],
            r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$",
        )


if __name__ == "__main__":
    unittest.main()
